import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import{randomBytes,randomUUID,scrypt as scryptCb,timingSafeEqual,createHash}from'node:crypto';import{promisify}from'node:util';import{sqlite,dataDir}from'./storage';import{GET,POST}from'./shop';
const scrypt=promisify(scryptCb),sha=(v:string)=>createHash('sha256').update(v).digest('hex'),json=(v:any,status=200)=>Response.json(v,{status});
const port=Number(process.env.PORT||3000),client=path.resolve('dist/client'),secure=process.env.SECURE_COOKIE==='true';
const expiry=()=>Date.now()+7*86400000;
const limits=new Map<string,{n:number,until:number}>();function rate(ip:string){const now=Date.now();if(limits.size>10000)for(const [k,v]of limits)if(v.until<now)limits.delete(k);let x=limits.get(ip);if(!x||x.until<now){x={n:0,until:now+60000};limits.set(ip,x)}return ++x.n<=12}
async function hashPassword(v:string){const salt=randomBytes(16).toString('hex');const hash=await scrypt(v,salt,64) as Buffer;return salt+':'+hash.toString('hex')}
async function matches(v:string,stored:string){const [salt,hash]=stored.split(':');const b=await scrypt(v,salt,64) as Buffer;const a=Buffer.from(hash,'hex');return a.length===b.length&&timingSafeEqual(a,b)}
const passwordValid=(v:any)=>typeof v==='string'&&v.length>=10&&v.length<=128;
const cookie=(token:string,max=7*86400)=>`shopmate_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${max}${secure?'; Secure':''}`;
function sessionUser(req:Request){const token=(req.headers.get('cookie')||'').match(/(?:^|;\s*)shopmate_session=([A-Za-z0-9_-]+)/)?.[1];if(!token)return null;return sqlite.prepare('SELECT users.id,users.email,users.name FROM sessions JOIN users ON users.id=sessions.user WHERE sessions.token=? AND sessions.expires>?').get(sha(token),Date.now()) as any||null}
function startSession(user:any){const token=randomBytes(32).toString('base64url');sqlite.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());sqlite.prepare('INSERT INTO sessions(token,user,expires) VALUES(?,?,?)').run(sha(token),user.id,expiry());return new Response(JSON.stringify({user:{id:user.id,email:user.email,name:user.name}}),{headers:{'Content-Type':'application/json','Set-Cookie':cookie(token)}})}
function inviteFor(email:string,code:string){const i=sqlite.prepare('SELECT * FROM invites WHERE email=? AND expires>?').get(email,Date.now()) as any;if(!i||!code||sha(code)!==i.hash)throw Error('The invitation code is invalid or expired.');return i}
function activate(user:any,i:any){sqlite.prepare('INSERT INTO members(email,business,role,sections) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET business=excluded.business,role=excluded.role,sections=excluded.sections').run(user.email,i.business,i.role,i.sections);sqlite.prepare('DELETE FROM invites WHERE email=?').run(user.email)}
async function auth(req:Request,ip:string){const route=new URL(req.url).pathname;const user=sessionUser(req);
 if(route==='/api/auth/me')return json({user});
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 if(route==='/api/auth/logout'){const token=(req.headers.get('cookie')||'').match(/shopmate_session=([A-Za-z0-9_-]+)/)?.[1];if(token)sqlite.prepare('DELETE FROM sessions WHERE token=?').run(sha(token));return new Response('{}',{headers:{'Content-Type':'application/json','Set-Cookie':cookie('',0)}})}
 if(route==='/api/auth/recovery'){if(!user)return json({error:'Sign in required'},401);const code=randomBytes(24).toString('base64url');sqlite.prepare('UPDATE users SET recovery=? WHERE id=?').run(sha(code),user.id);return json({code})}
 if(!rate(ip))return json({error:'Too many attempts. Please wait a minute.'},429);
 if(!req.headers.get('content-type')?.includes('application/json'))return json({error:'Invalid request'},400);
 const a:any=await req.json();const email=String(a.email||'').trim().toLowerCase();
 if(route==='/api/auth/accept-invite'){if(!user)return json({error:'Sign in required'},401);const i=inviteFor(user.email,String(a.code||''));activate(user,i);return json({ok:true})}
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)return json({error:'Enter a valid email.'},400);
 const row=sqlite.prepare('SELECT * FROM users WHERE email=?').get(email) as any;
 if(route==='/api/auth/signup'){if(!passwordValid(a.password))return json({error:'Use a password with 10 to 128 characters.'},400);if(row)return json({error:'This email is registered. Sign in or use your recovery code.'},409);if(!String(a.name||'').trim())return json({error:'Enter your name.'},400);let invite=null;if(a.invite)invite=inviteFor(email,String(a.invite));const id=randomUUID(),password=await hashPassword(a.password);sqlite.exec('BEGIN IMMEDIATE');try{sqlite.prepare('INSERT INTO users(id,email,name,password,created) VALUES(?,?,?,?,?)').run(id,email,String(a.name).trim().slice(0,100),password,new Date().toISOString());if(invite)activate({email},invite);sqlite.exec('COMMIT')}catch(e){sqlite.exec('ROLLBACK');throw e}return startSession({id,email,name:a.name})}
 if(route==='/api/auth/login'){if(typeof a.password!=='string'||a.password.length>128)return json({error:'Incorrect email or password.'},401);const dummy='8fac43c1b24b23017f673f4923a4afea:'+('0'.repeat(128));const valid=await matches(a.password,row?.password||dummy);if(!row||!valid)return json({error:'Incorrect email or password.'},401);return startSession(row)}
 if(route==='/api/auth/reset'){if(!passwordValid(a.password))return json({error:'Use a password with 10 to 128 characters.'},400);if(!row?.recovery||sha(String(a.recovery||''))!==row.recovery)return json({error:'Incorrect email or recovery code.'},400);const password=await hashPassword(a.password);sqlite.exec('BEGIN IMMEDIATE');try{sqlite.prepare('UPDATE users SET password=?,recovery=NULL WHERE id=?').run(password,row.id);sqlite.prepare('DELETE FROM sessions WHERE user=?').run(row.id);sqlite.exec('COMMIT')}catch(e){sqlite.exec('ROLLBACK');throw e}return json({ok:true})}
 return json({error:'Not found'},404)
}
async function shop(req:Request){const user=sessionUser(req);if(!user)return json({error:'Sign in required'},401);const h=new Headers(req.headers);h.delete('oai-authenticated-user-id');h.delete('oai-authenticated-user-email');h.set('oai-authenticated-user-id',user.id);h.set('oai-authenticated-user-email',user.email);let body:Uint8Array|undefined;if(req.method!=='GET')body=new Uint8Array(await req.arrayBuffer());const trusted=new Request(req.url,{method:req.method,headers:h,body});
 if(req.method==='POST'&&h.get('content-type')?.includes('application/json')){const a:any=JSON.parse(Buffer.from(body!).toString());if(a.type==='staff'){if(new URL(req.url).searchParams.get('demo')==='1')return json({error:'Use your real business for staff invitations.'},400);const member=sqlite.prepare('SELECT * FROM members WHERE email=?').get(user.email) as any;const id=member?.business||user.id;const b=sqlite.prepare('SELECT owner FROM businesses WHERE id=?').get(id) as any;if(b?.owner!==user.email)return json({error:'Owner access required'},403);const email=String(a.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email===user.email||!['Manager','Cashier'].includes(a.role))return json({error:'Enter a valid staff email and role'},400);const active=sqlite.prepare('SELECT business FROM members WHERE email=?').get(email) as any;if(active?.business===id)return POST(trusted);if(active)return json({error:'Staff already belong to another business.'},400);const code=randomBytes(20).toString('base64url');sqlite.prepare('INSERT INTO invites(email,business,hash,expires,role,sections) VALUES(?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET business=excluded.business,hash=excluded.hash,expires=excluded.expires,role=excluded.role,sections=excluded.sections').run(email,id,sha(code),expiry(),a.role,JSON.stringify(a.sections||[]));return json({ok:true,invite:code})}}
 if(req.method==='GET'){const r=await GET(trusted);if(!r.ok)return r;const j:any=await r.json();if(j.role==='Owner'){const member=sqlite.prepare('SELECT business FROM members WHERE email=?').get(user.email) as any;const id=member?.business||user.id;if(new URL(req.url).searchParams.get('demo')!=='1'){const pending=sqlite.prepare('SELECT email,role,sections FROM invites WHERE business=? AND expires>?').all(id,Date.now());j.members.push(...pending.map((x:any)=>({...x,role:x.role+' (invited)'})))}}return json(j)}if(req.method==='POST'){const a=h.get('content-type')?.includes('application/json')?JSON.parse(Buffer.from(body!).toString()):null;const r=await POST(trusted);if(r.ok&&a?.type==='removeStaff'){const member=sqlite.prepare('SELECT business FROM members WHERE email=?').get(user.email) as any;sqlite.prepare('DELETE FROM invites WHERE email=? AND business=?').run(a.email,member?.business||user.id)}return r}return json({error:'Method not allowed'},405)
}
const mime:any={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer(async(incoming,out)=>{try{const origin=process.env.PUBLIC_ORIGIN||'http://'+incoming.headers.host;const url=new URL(incoming.url||'/',origin);const headers=new Headers();for(const [k,v]of Object.entries(incoming.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);headers.delete('oai-authenticated-user-id');headers.delete('oai-authenticated-user-email');
 if(incoming.method==='POST'&&headers.get('origin')&&headers.get('origin')!==new URL(origin).origin){out.writeHead(403,{'Content-Type':'application/json'});out.end(JSON.stringify({error:'Invalid request origin'}));return}
 let size=0;const chunks:Buffer[]=[];for await(const c of incoming){const b=Buffer.from(c);size+=b.length;if(size>4*1024*1024){out.writeHead(413);out.end('Request too large');return}chunks.push(b)}
 const req=new Request(url,{method:incoming.method,headers,body:['GET','HEAD'].includes(incoming.method||'GET')?undefined:Buffer.concat(chunks)});let r:Response;
 if(url.pathname.startsWith('/api/auth/'))r=await auth(req,incoming.socket.remoteAddress||'unknown');else if(url.pathname==='/api/shop')r=await shop(req);else if(url.pathname==='/health')r=json({ok:true});else{let file=path.resolve(client,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(client+path.sep)&&file!==client)r=new Response('Not found',{status:404});else{if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(client,'index.html');r=new Response(fs.readFileSync(file),{headers:{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':url.pathname.startsWith('/assets/')?'public,max-age=31536000,immutable':'no-cache'}})}}
 const responseHeaders:any=Object.fromEntries(r.headers);responseHeaders['X-Content-Type-Options']='nosniff';responseHeaders['Referrer-Policy']='same-origin';responseHeaders['X-Frame-Options']='DENY';responseHeaders['Content-Security-Policy']="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'";if(url.pathname.startsWith('/api/'))responseHeaders['Cache-Control']='no-store';out.writeHead(r.status,responseHeaders);out.end(Buffer.from(await r.arrayBuffer()))
}catch(e:any){console.error('Request failed:',e.message);out.writeHead(400,{'Content-Type':'application/json','Cache-Control':'no-store'});out.end(JSON.stringify({error:'Unable to complete the request. Please try again.'}))}});
server.listen(port,'0.0.0.0',()=>console.log('Jathan ShopMate listening on port '+port));const shutdown=()=>server.close(()=>{sqlite.close();process.exit(0)});process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
