import {env} from './storage';
const db=()=> (env as any).DB;
const uid=()=>crypto.randomUUID();
const blank=()=>({name:'My shop',sections:['Provisions','Frozen & Other Items'],products:[],sales:[],expenses:[],movements:[],counts:[],audit:[]});
const fail=(s:string)=>{throw new Error(s)};
async function context(req:Request){
 const user=req.headers.get('oai-authenticated-user-id');const email=req.headers.get('oai-authenticated-user-email')?.toLowerCase();
 if(!user||!email) return null;
 const member=await db().prepare('SELECT * FROM members WHERE email=?').bind(email).first();
 const demo=new URL(req.url).searchParams.get('demo')==='1';const id=demo?user+'-demo':member?.business||user; let row=await db().prepare('SELECT * FROM businesses WHERE id=?').bind(id).first();
 if(!row){await db().prepare('INSERT OR IGNORE INTO businesses(id,owner,data,version) VALUES(?,?,?,0)').bind(id,email,JSON.stringify(blank())).run();row=await db().prepare('SELECT * FROM businesses WHERE id=?').bind(id).first()}
 return {id,email,role:demo||row.owner===email?'Owner':member?.role||'Cashier',sections:JSON.parse(member?.sections||'[]'),row};
}
function visible(c:any,s:any){if(c.role==='Owner'||c.role==='Manager')return s;return {...s,products:s.products.filter((p:any)=>c.sections.includes(p.section)).map(({cost,...p}:any)=>p),sales:s.sales.filter((x:any)=>x.by===c.email).map(({cost,...x}:any)=>({...x,items:x.items.map(({cost,...i}:any)=>i),refunds:x.refunds.map(({cost,...r}:any)=>r)})),expenses:[],movements:[],counts:[],audit:[]}}
export async function GET(req:Request){try{const c=await context(req);if(!c)return Response.json({error:'Please sign in with ChatGPT.'},{status:401});const s=JSON.parse(c.row.data);const image=new URL(req.url).searchParams.get('image');if(image){if(!image.startsWith(c.id+'/'))return Response.json({error:'Forbidden'},{status:403});const obj=await (env as any).BUCKET.get(image);if(!obj)return new Response('Not found',{status:404});return new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata?.contentType||'image/jpeg','Cache-Control':'private, max-age=3600','X-Content-Type-Options':'nosniff'}})}const members=c.role==='Owner'?(await db().prepare('SELECT email,role,sections FROM members WHERE business=?').bind(c.id).all()).results:[];return Response.json({data:visible(c,s),role:c.role,email:c.email,members,version:c.row.version})}catch{return Response.json({error:'Unable to load your shop. Please try again.'},{status:503})}}
export async function POST(req:Request){try{
 const c=await context(req);if(!c)return Response.json({error:'Sign in required'},{status:401});
 if(req.headers.get('origin')&&new URL(req.url).origin!==req.headers.get('origin'))return Response.json({error:'Invalid request'},{status:403});
 if(req.headers.get('content-type')?.includes('multipart/form-data')){if(!['Owner','Manager'].includes(c.role))return Response.json({error:'Manager access required'},{status:403});const f=(await req.formData()).get('photo') as File;if(!f||f.size>3000000||!['image/jpeg','image/png','image/webp'].includes(f.type))return Response.json({error:'Choose a JPG, PNG or WebP under 3 MB'},{status:400});const key=c.id+'/'+uid();await (env as any).BUCKET.put(key,await f.arrayBuffer(),{httpMetadata:{contentType:f.type}});return Response.json({key})}const a:any=await req.json();const s=JSON.parse(c.row.data);const now=new Date().toISOString();const businessDate=new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Lagos'});
 const owner=()=>{if(c.role!=='Owner')fail('Only the owner can do this.')};const manage=()=>{if(!['Owner','Manager'].includes(c.role))fail('Manager access required.')};
 const num=(v:any,min=0)=>{const n=Number(v);if(!Number.isFinite(n)||n<min)fail('Enter a valid amount or quantity.');return n};
 const product=(id:string)=>s.products.find((p:any)=>p.id===id)||fail('Product not found');
 const move=(p:any,q:number,type:string,reason:string,photo='')=>s.movements.unshift({id:uid(),product:p.id,name:p.name,section:p.section,quantity:q,type,reason,photo,at:now,by:c.email});
 if(a.type==='staff'){owner();if(new URL(req.url).searchParams.get('demo')==='1')fail('Staff access is available in your real business.');const email=String(a.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email===c.row.owner)fail('Enter a different valid staff email.');if(!['Manager','Cashier'].includes(a.role))fail('Invalid staff role');const existing=await db().prepare('SELECT business FROM members WHERE email=?').bind(email).first();if(existing&&existing.business!==c.id)fail('This email already belongs to another shop.');await db().prepare('INSERT INTO members(email,business,role,sections) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET role=excluded.role,sections=excluded.sections').bind(email,c.id,a.role,JSON.stringify(a.sections||s.sections)).run();return Response.json({ok:true})}
 if(a.type==='removeStaff'){owner();await db().prepare('DELETE FROM members WHERE email=? AND business=?').bind(a.email,c.id).run();return Response.json({ok:true})}
 if(a.type==='settings'){owner();s.name=String(a.name||'My shop').slice(0,100);if(a.sections){if(!Array.isArray(a.sections)||!a.sections.length)fail('At least one section required');s.sections=[...new Set(a.sections.map((x:any)=>String(x).trim()).filter(Boolean))];if(s.products.some((p:any)=>!s.sections.includes(p.section)))fail('Move products before removing a section.')}}
 if(a.type==='product'){manage();if(!s.sections.includes(a.section))fail('Choose a section');const q=num(a.quantity),cost=num(a.cost),price=num(a.price);if(!String(a.name||'').trim())fail('Product name required');const unit=String(a.unit||'piece');if(a.image&&!String(a.image).startsWith(c.id+'/'))fail('Invalid image');if(!['kg','g'].includes(unit)&&q%1)fail('This unit needs a whole quantity');const units=[{name:unit,factor:1,price}];for(const u of a.units||[]){if(!u.name||units.some(x=>x.name===u.name))fail('Unit names must be unique');units.push({name:String(u.name),factor:num(u.factor,0.000001),price:num(u.price)})}const p={id:uid(),name:String(a.name).trim(),category:a.category||'',section:a.section,sku:a.sku||'',image:a.image||'',unit,units,cost,quantity:q,threshold:num(a.threshold),batches:[],expiryTracked:!!a.expiry};if(a.expiry){if(a.expiry<businessDate)fail('Opening stock is expired');p.batches.push({id:uid(),quantity:q,expiry:a.expiry} as never)}s.products.push(p);move(p,q,'Opening stock','Initial physical count')}
 if(a.type==='receive'){manage();const p=product(a.product);const u=p.units.find((u:any)=>u.name===a.unit)||fail('Invalid unit');const q=num(a.quantity,0.000001)*u.factor;const cost=num(a.cost)/u.factor;if(!['kg','g'].includes(p.unit)&&q%1)fail('Quantity must convert to whole items');if(p.expiryTracked&&!a.expiry)fail('Expiry date required');if(a.expiry&&a.expiry<businessDate)fail('Cannot receive expired stock');p.cost=(p.quantity*p.cost+q*cost)/(p.quantity+q);p.quantity+=q;if(a.expiry){p.expiryTracked=true;p.batches.push({id:uid(),quantity:q,expiry:a.expiry})}move(p,q,'Received',`${a.supplier||'Supplier'} · ${a.reference||'No invoice reference'}`)}
 const deduct=(p:any,q:number)=>{if(p.quantity+1e-8<q)fail(`${p.name}: insufficient stock`);if(p.expiryTracked){let remaining=q;const bs=p.batches.filter((b:any)=>b.expiry>=businessDate).sort((x:any,y:any)=>x.expiry.localeCompare(y.expiry));if(bs.reduce((n:number,b:any)=>n+b.quantity,0)+1e-8<q)fail(`${p.name}: insufficient unexpired stock`);for(const b of bs){const use=Math.min(remaining,b.quantity);b.quantity-=use;remaining-=use}}p.quantity=Math.max(0,p.quantity-q)};
 if(a.type==='sale'){if(s.sales.some((x:any)=>x.id===a.id))return Response.json({ok:true,duplicate:true});if(!Array.isArray(a.items)||!a.items.length)fail('Cart is empty');const items=[];for(const i of a.items){const p=product(i.product);if(c.role==='Cashier'&&!c.sections.includes(p.section))fail('Section not permitted');const u=p.units.find((u:any)=>u.name===i.unit)||fail('Invalid unit');const count=num(i.quantity,0.000001);if(i.price!==undefined&&c.role==='Cashier')fail('Only managers can override prices');const price=i.price!==undefined?num(i.price):u.price;const q=count*u.factor;if(!['kg','g'].includes(p.unit)&&q%1)fail('Whole quantities required');deduct(p,q);items.push({product:p.id,name:p.name,section:p.section,unit:u.name,quantity:count,baseQuantity:q,price,total:count*price,cost:q*p.cost,returned:0});move(p,-q,'Sale',a.id)}const subtotal=items.reduce((n,i)=>n+i.total,0);const discount=num(a.discount||0);if(discount&&c.role==='Cashier')fail('Only managers can discount sales');if(discount>subtotal)fail('Discount exceeds sale value');for(const i of items){const share=subtotal?discount*i.total/subtotal:0;i.total-=share;i.price=i.total/i.quantity}const total=subtotal-discount;const paid=(a.payments||[]).reduce((n:number,x:any)=>n+num(x.amount),0);if(Math.abs(paid-total)>0.01)fail('Payments must equal the sale total');s.sales.unshift({id:a.id||uid(),items,total,cost:items.reduce((n,i)=>n+i.cost,0),discount,payments:a.payments,at:now,by:c.email,refunds:[]})}
 if(a.type==='return'){manage();const sale=s.sales.find((x:any)=>x.id===a.sale)||fail('Sale not found');const i=sale.items[Number(a.index)]||fail('Item not found');const q=num(a.quantity,0.000001);if(!['kg','g'].includes(product(i.product).unit)&&(q*i.baseQuantity/i.quantity)%1)fail('Return must convert to whole items');if(q>i.quantity-i.returned+1e-8)fail('Return exceeds remaining sold quantity');if(!a.reason)fail('Reason required');const p=product(i.product),base=q*i.baseQuantity/i.quantity;i.returned+=q;const refund={id:uid(),product:i.product,section:i.section,quantity:q,amount:q*i.price,cost:q*i.cost/i.quantity,resellable:!!a.resellable,at:now,reason:a.reason};sale.refunds.push(refund);if(a.resellable){if(p.expiryTracked&&(!a.expiry||a.expiry<businessDate))fail('Valid expiry required for return');p.cost=(p.quantity*p.cost+refund.cost)/(p.quantity+base);p.quantity+=base;if(p.expiryTracked)p.batches.push({id:uid(),quantity:base,expiry:a.expiry});move(p,base,'Return',a.reason)}else move(p,0,'Non-resellable return',a.reason)}
 if(a.type==='damage'){manage();const p=product(a.product),q=num(a.quantity,0.000001);if(!a.reason)fail('Reason required');if(!['kg','g'].includes(p.unit)&&q%1)fail('Whole quantities required');if(a.photo&&!String(a.photo).startsWith(c.id+'/'))fail('Invalid photo');if(q>p.quantity)fail('Insufficient stock');p.quantity-=q;if(p.expiryTracked){let r=q;for(const b of [...p.batches].sort((x:any,y:any)=>x.expiry.localeCompare(y.expiry))){const u=Math.min(r,b.quantity);b.quantity-=u;r-=u}}move(p,-q,'Spoilage / damage',a.reason,a.photo||'');s.expenses.unshift({id:uid(),category:'Stock loss',amount:q*p.cost,section:p.section,at:now,note:a.reason,by:c.email})}
 if(a.type==='countStart'){manage();s.counts.unshift({id:uid(),section:a.section,status:'Counting',at:now,by:c.email,items:s.products.filter((p:any)=>p.section===a.section).map((p:any)=>({product:p.id,name:p.name,expected:p.quantity,actual:null})),movementIds:s.movements.map((m:any)=>m.id)})}
 if(a.type==='countSubmit'){manage();const count=s.counts.find((x:any)=>x.id===a.id)||fail('Count not found');if(count.status!=='Counting')fail('Count already submitted');count.items=count.items.map((i:any)=>({...i,actual:num(a.actual[i.product])}));count.reason=a.reason||'Physical count';count.status='Awaiting approval'}
 if(a.type==='countApprove'){owner();const count=s.counts.find((x:any)=>x.id===a.id)||fail('Count not found');if(count.status!=='Awaiting approval')fail('Count is not awaiting approval');if(s.movements.some((m:any)=>!count.movementIds.includes(m.id)&&m.section===count.section))fail('Stock changed during this count. Start a fresh count when this section is paused.');for(const i of count.items){const p=product(i.product);if(p.expiryTracked&&i.actual!==p.quantity)fail('For expiry-tracked goods, correct batches through receiving or spoilage, then start a fresh count.');if(!['kg','g'].includes(p.unit)&&i.actual%1)fail('Count must use whole items');const delta=i.actual-p.quantity;if(delta<0)s.expenses.unshift({id:uid(),category:'Stock count loss',amount:-delta*p.cost,section:p.section,at:now,note:count.reason,by:c.email});p.quantity=i.actual;move(p,delta,'Count adjustment',count.reason)}count.status='Approved';count.approvedBy=c.email}
 if(a.type==='expense'){manage();s.expenses.unshift({id:uid(),category:a.category||'Other',amount:num(a.amount,0.01),section:a.section||'Business',note:a.note||'',at:now,by:c.email})}
 if(a.type==='price'){owner();const p=product(a.product);p.units=p.units.map((u:any)=>({...u,price:num(a.prices[u.name])}));p.threshold=num(a.threshold);p.name=String(a.name||p.name).trim()}
 if(a.type==='transfer'){manage();const p=product(a.product),q=num(a.quantity,0.000001);if(!s.sections.includes(a.section)||a.section===p.section)fail('Choose a different section');const before=p.batches.map((b:any)=>({...b}));if(!['kg','g'].includes(p.unit)&&q%1)fail('Whole quantities required');deduct(p,q);let dest=s.products.find((d:any)=>d.sourceProduct===p.id&&d.section===a.section);if(!dest){dest={...p,id:uid(),sourceProduct:p.id,section:a.section,quantity:0,batches:[],units:p.units.map((u:any)=>({...u}))};s.products.push(dest)}dest.cost=(dest.quantity*dest.cost+q*p.cost)/(dest.quantity+q);dest.quantity+=q;for(const b of before){const after=p.batches.find((x:any)=>x.id===b.id);const moved=b.quantity-(after?.quantity||0);if(moved>0)dest.batches.push({id:uid(),quantity:moved,expiry:b.expiry})}move(p,-q,'Transfer out',a.section);move(dest,q,'Transfer in',p.section)}
 if(a.type==='countCancel'){manage();const count=s.counts.find((x:any)=>x.id===a.id)||fail('Count not found');if(count.status==='Approved')fail('Approved counts cannot be cancelled');count.status='Cancelled'}
 const known=['price','transfer','countCancel','settings','product','receive','sale','return','damage','countStart','countSubmit','countApprove','expense'];if(!known.includes(a.type))fail('Unknown action');
 s.audit.unshift({id:uid(),action:a.type,at:now,by:c.email});
 const result=await db().prepare('UPDATE businesses SET data=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(s),c.id,c.row.version).run();if(!result.meta.changes)return Response.json({error:'Another staff member updated the shop. Refresh and try again.'},{status:409});return Response.json({ok:true});
 }catch(e:any){return Response.json({error:e.message||'Unable to save. Please try again.'},{status:400})}}
